src/main/resources/static/openapi.json
- swagger api 작성
- swagger api 작성
- #4 
-
=> [DOCS] 홈화면, 나의 통계, 사용자 통계 관련 API 명세서 작성

src/main/resources/static/openapi.json
API url, 명세 및 DTO 작성
- 뉴스, 단어통계 관련 API 명세서 작성
- HTTP 메소드가 적절한가?
- url 형식이 통일성이 있으며, 적절하게 작성되었는가?
- DTO가 빠짐없이 작성되었는가?
- #2 
- DTO 예시는 상세 화면 명세 이후 추가 예정입니다.
=> [DOCS] 뉴스, 단어통계 관련 API 명세서 작성

src/main/java/com/movelog/global/config/security/SecurityConfig.java
- 스웨거 경로 시큐리티 허용
- 스웨거 경로 명시적 허용
-
-
=> [DOCS] 스웨거 경로 시큐리티 허용

src/main/java/com/movelog/MoveLogApplication.java, src/main/resources/swagger/application-springdoc.yml
- 개발 현황 확인을 위한 스웨거 API 명세서 설정
-
-
-
=> [DOCS] 개발 현황 확인을 위한 스웨거 API 명세서 설정

src/main/java/com/movelog/global/config/security/SecurityConfig.java
- 개발 현황 확인을 위한 스웨거 API 명세 자동화 설정
- 개발 현황 확인을 위한 스웨거 API 명세 자동화 설정
-
-
=> [DOCS] 개발 현황 확인을 위한 스웨거 API 명세 자동화 설정

src/main/java/com/movelog/global/config/security/SecurityConfig.java
- 개발 현황을 위한 스웨거 api 명세서 자동화 시큐리티 허용
-
-
-
=> [DOCS] 개발 현황을 위한 스웨거 api 명세서 자동화 시큐리티 허용

src/main/resources/application.yml, src/main/resources/swagger/application-springdoc.yml
- openapi, swagger 자동화 문서 모두 접속 가능하도록 수정
- 엔트포인트 충돌 방지
- 하나의 페이지에서 두 버전 모두 접속 가능
-
- #4 
-
=> [DOCS] openapi, swagger 자동화 문서 모두 접속 가능하도록 수정

src/main/resources/static/openapi.json
=> [DOCS]카카오 로그인 문서 작성

src/main/resources/static/openapi.json
=> Merge develop to main

src/main/resources/static/openapi.json
- API 명세서 내 배포 주소 정보 수정
- API 명세서 주소는 다음과 같습니다.
- http://52.78.107.187:8080/swagger-ui/index.html?urls.primaryName=Custom%20OpenAPI%20Docs#/News/post_news__imageId_
- #4
-
=> [DOCS] API 명세서 내 배포 주소 정보 수정

src/main/java/com/movelog/domain/record/domain/Record.java, src/main/java/com/movelog/domain/record/presentation/RecordController.java, src/main/java/com/movelog/domain/record/repository/RecordRepository.java, src/main/java/com/movelog/domain/record/service/RecordService.java
- 오늘까지의 기록현황 api 구현한다.
- x
- #28 
-
=> [FEAT] 오늘까지의 기록현황 api 구현

src/main/java/com/movelog/domain/record/presentation/RecordController.java
- 사진이 필수가 아니여서 수정합니다!
-
- #28 
-
=> [FIX] 사진 필수 -> 사진 필수X

src/main/java/com/movelog/domain/auth/presentation/AuthController.java
=> [FIX] 토큰시간 1달로 변경

Dockerfile
=> Merge main to develop

.github/workflows/deploy.yml, Dockerfile, appspec.yml
- CICD 구축에 따른 충돌 방지를 위한 PR
- 가상 도커 사용(AWS ECR)
- Git Actions를 통한 배포 자동화
- 
- #36 
- ECR 적용에 시간이 걸려 우선 자동 배포 구축만 해둔 상태이며,
아직 무중단 배포 상황은 아닙니다.
- 따라서, 배포 완료 후 약간의 시간이 걸리므로 기다려 주셔야 합니다.
- 본 PR을 CICD 구축을 위해 main 브랜치에서 작업되었기 때문에 이후 pull 시 충돌 방지를 위해 올립니다.
=> [CICD] CICD 구축에 따른 충돌 방지를 위한 PR

src/main/java/com/movelog/domain/gpt/application/GptService.java, src/main/java/com/movelog/domain/news/application/HeadlineGeneratorService.java, src/main/java/com/movelog/domain/news/application/NewsService.java, src/main/java/com/movelog/domain/news/dto/request/NewsHeadLineReq.java, src/main/java/com/movelog/domain/news/dto/response/HeadLineRes.java, src/main/java/com/movelog/domain/news/presentation/NewsController.java, src/main/java/com/movelog/domain/user/application/UserService.java, src/main/java/com/movelog/domain/user/exception/UserDuplicateException.java, src/main/java/com/movelog/domain/user/exception/UserNotFoundException.java, src/main/java/com/movelog/global/exception/DuplicateException.java, src/main/java/com/movelog/global/exception/NotFoundException.java, src/main/resources/static/openapi.json
- 기록 옵션, 동사, 명사 정보를 기반하여 3개의 헤드라인을 생성하여 추천하는 기능입니다.
- 응답값으로 headline이 리스트 형식으로 나오며, 이에 따라 openAPI 문서 수정이 이루어졌습니다.
- 요청 및 응답 내용이 빠짐없이 잘 이루어졌는가?
- #38 #39 
- 요청 결과를 보니 응답값에 동사, 명사 결과가 명확하게 표현되지 않습니다.
- 이에 따라 프롬포트 수정 예정입니다.
=> [FEAT] 뉴스 헤드라인 추천 기능 구현

src/main/java/com/movelog/domain/record/domain/Record.java, src/main/java/com/movelog/domain/record/domain/VerbType.java, src/main/java/com/movelog/domain/record/dto/request/CreateRecordReq.java, src/main/java/com/movelog/domain/record/presentation/RecordController.java, src/main/java/com/movelog/domain/record/service/RecordService.java
- VerbType enum 사용에 따른 기록 생성 기능 수정
- enum type 수정이 DB 측면에서도 제대로 update되었는가?
- 
- 기존 Long 타입으로 바뀐 내용을 다시 수정했습니다.
- 코드 가독성 및 유지보수 측면에서 고정된 옵션인 동사 타입은 Enum으로 처리하는 게 낫다고 판단하였습니다.
=> [REFACTOR] VerbType enum 사용에 따른 기록 생성 기능 수정

src/main/java/com/movelog/domain/news/application/NewsService.java, src/main/java/com/movelog/domain/news/domain/repository/NewsRepository.java, src/main/java/com/movelog/domain/news/dto/response/NewsCalendarRes.java, src/main/java/com/movelog/domain/news/dto/response/TodayNewsStatusRes.java, src/main/java/com/movelog/domain/news/presentation/NewsController.java
- 뉴스 현황 조회 기능 구현
- 날짜별 뉴스 목록 조회 기능 구현
- 페이징 기능 반영
- 
- #56 
-
=> [FEAT] 뉴스 현황 조회 기능 및 날짜별 뉴스 목록 조회 기능 구현

src/main/java/com/movelog/domain/record/dto/response/RecordCalendarRes.java, src/main/java/com/movelog/domain/record/presentation/RecordController.java, src/main/java/com/movelog/domain/record/repository/RecordRepository.java, src/main/java/com/movelog/domain/record/service/RecordService.java
- 날짜별 기록 조회 기능 구현
- 사용자 검증 로직이 통일되었는가?
- 응답값이 빠짐없이 모두 포함되었는가?
- #64 
-
=> [FEAT] 날짜별 기록 조회 기능 구현

src/main/java/com/movelog/domain/record/dto/response/Recent5RecordImagesRes.java, src/main/java/com/movelog/domain/record/presentation/RecordController.java, src/main/java/com/movelog/domain/record/repository/RecordRepository.java, src/main/java/com/movelog/domain/record/service/RecordService.java
- 사용자의 최신 기록 이미지 5개 조회 기능 구현
-
- #69 
-
=> [FEAT] 사용자의 최신 기록 이미지 5개 조회 기능 구현

.github/workflows/deploy.yml, build.gradle, src/main/java/com/movelog/MoveLogApplication.java, src/main/java/com/movelog/domain/news/application/NewsService.java, src/main/java/com/movelog/domain/record/application/KeywordService.java, src/main/java/com/movelog/domain/record/application/RecordService.java, src/main/java/com/movelog/domain/record/domain/repository/KeywordRepository.java, src/main/java/com/movelog/domain/record/domain/repository/RecordRepository.java, src/main/java/com/movelog/domain/record/dto/response/SearchKeywordInStatsRes.java, src/main/java/com/movelog/domain/record/presentation/KeywordController.java, src/main/java/com/movelog/domain/record/presentation/RecordController.java, src/main/java/com/movelog/global/config/RedisConfig.java
- 나의 단어 통계 조회를 위한 단어 검색 기능 구현
- 
- #73 #74 
- 사용자 개인 기록의 통계 조회 시에는 redis가 사용되지 않습니다.
=> [FEAT] 나의 단어 통계 조회를 위한 단어 검색 기능 구현

src/main/java/com/movelog/domain/record/application/KeywordService.java, src/main/java/com/movelog/domain/record/dto/response/RecommendKeywordInStatsRes.java, src/main/java/com/movelog/domain/record/presentation/StatsController.java
- 통계 단어 검색 시 최근 사용자가 기록한 단어 목록 조회 기능 구현
-
- #80 
-
=> [FEAT] 통계 단어 검색 시 최근 사용자가 기록한 단어 목록 조회 기능 구현

src/main/java/com/movelog/domain/record/application/RecordService.java, src/main/java/com/movelog/domain/record/presentation/RecordController.java
=> [FIX] 기록 생성 시 이미지 null 허용

src/main/java/com/movelog/MoveLogApplication.java, src/main/java/com/movelog/domain/record/application/DataMigrationService.java, src/main/java/com/movelog/domain/record/application/RecordService.java, src/main/java/com/movelog/domain/record/domain/repository/RecordRepository.java, src/main/java/com/movelog/domain/record/dto/response/AllUserRecordStatsRes.java, src/main/java/com/movelog/domain/record/presentation/StatsController.java, src/main/java/com/movelog/global/config/RedisConfig.java, src/main/resources/application.yml
- 사용자 전체 기록에 대한 통계 정보 조회 기능 구현
-
- #90 
-
=> [FEAT] 사용자 전체 기록에 대한 통계 정보 조회 기능 구현

src/main/java/com/movelog/domain/news/application/NewsService.java, src/main/java/com/movelog/domain/record/application/DataMigrationService.java, src/main/java/com/movelog/domain/record/application/RecordService.java, src/main/java/com/movelog/global/config/RedisConfig.java
- 기록 키워드 순위 조회 시 이전 순위 변동 여부 함께 응답
- 
- #90 
-
=> [FEAT] 기록 키워드 순위 조회 시 이전 순위 변동 여부 함께 응답

src/main/java/com/movelog/domain/record/application/KeywordService.java, src/main/java/com/movelog/domain/record/domain/repository/KeywordRepository.java, src/main/java/com/movelog/domain/record/domain/repository/RecordRepository.java
- 키워드 문자열 기준 검색 결과 그룹화 및 통계 결과 그룹화 수정 반영
- 테스트 유저 ID 고정이 해제되었는갸?
- 테스트 결과가 잘 나오는가?
-
-
=> [FIX] 키워드 문자열 기준 검색 결과 그룹화 및 통계 결과 그룹화 수정 반영

src/main/java/com/movelog/domain/news/application/NewsService.java
- 기존: 5개 다 채워진 후에 다음 날 0개로 초기화
- 변경 후: 5개 모두 채워진 후에 다음 뉴스 생성 시 1개로 시작
-
- #102 
-
=> [FIX] 뉴스 스탬프 현황 관련 명세 변경에 따른 수정사항 반영

src/main/java/com/movelog/domain/news/application/HeadLineGeneratorService.java, src/main/java/com/movelog/domain/news/application/NewsService.java, src/main/java/com/movelog/domain/news/dto/response/HeadLineRes.java, src/main/java/com/movelog/domain/record/application/RecordService.java, src/main/java/com/movelog/domain/record/domain/repository/RecordRepository.java
- 뉴스 헤드라인 생성프롬포트 분리 및 수정, 부가적 일수 계산 메소드 구현
-
- #101 
-
=> [FIX] 뉴스 헤드라인 생성프롬포트 분리 및 수정, 부가적 일수 계산 메소드 구현
